import javax.swing.*;
public class JOptionPaneExample {

  public static void main(String[] args) {
    /* JOptionPane Java user input example */
    
            System.out.print(s:"Hello World!");
  
    var name = JOptionPane.showInputDialog(null,"i kiss cute boys");
    var output = name + "nigga thats gay";
    JOptionPane.showMessageDialog(null, output);
    //- only for testing fix if nessisary but plss leave comments or notes 
  }

}
      
